### ISSUE TITLE
Request for TaskView

### ISSUE THREAD

**Issue by ghost** [bw-hro/WeKanboard#2]
Hello,

I really like the theme. Do you plan to extend the CSS for the taskview, too? At the moment it seems like only the outer frame and the board view is supported. When I have a look at the task pages, the upper part of the task still looks like the kanboard default themen.

Thanks a lot!

**Comment by bw-hro** [comment]
Hi, you are talking about the summary box in task detail view right? This box should be more in the style of the task cards in the board view? When I find some time I could experiment a little with the style of the box.

In case you mean to directly open the task detail page in board view like it is done in Wekan, than no I have no plans to add something like this at the moment, as I assume that this would require some more effort.

**Comment by bw-hro** [comment]
if you like you could replace your WeKanboard.css with that one from master branch and check if the result is as expected.

**Comment by ghost** [comment]
Good morning,

thanks for your answer. It is definitly the first thing I am talking about. I experimented with it a little by myself and found out, that applying the same CSS attributes as for the task card in the board view does 90% of the job. I know, that is very little of a help...

Thanks for your time!

**Comment by ghost** [comment]
> 
> 
> if you like you could replace your WeKanboard.css with that one from master branch and check if the result is as expected.

Good morning,

I tested the new CSS a few minutes ago. It looks good! Now the task board and the detailed task pages share the same design.

Thank you very much!

**Comment by bw-hro** [comment]
TBinconso, thank you very much for your feedback. In next release new layout will be included.
